application: gcalupdate
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /.*
  script: cal.app

libraries:
- name: jinja2
  version: latest